// Đề 8: GROUP POLICY OBJECT (GPO) - 30 câu
const questionsSet8 = [
    { question: "GPO là gì?", options: ["Công cụ quản lý DHCP", "Cơ chế quản lý tập trung cấu hình user và computer", "Dịch vụ DNS", "Công cụ sao lưu AD"], correct: 1 },
    { question: "GPO có thể áp dụng cho đối tượng nào?", options: ["User", "Computer", "Site / Domain / OU", "Tất cả các đáp án trên"], correct: 3 },
    { question: "GPO gồm mấy phần chính?", options: ["1", "2", "3", "4"], correct: 1 },
    { question: "Computer Configuration áp dụng khi nào?", options: ["Khi user đăng nhập", "Khi máy khởi động", "Khi đổi mật khẩu", "Khi join domain"], correct: 1 },
    { question: "User Configuration được áp dụng khi nào?", options: ["Khi máy khởi động", "Khi user đăng nhập", "Khi cài Windows", "Khi join domain"], correct: 1 },
    { question: "GPO có thể link vào đâu?", options: ["OU", "Domain", "Site", "Tất cả các đáp án trên"], correct: 3 },
    { question: "Thứ tự xử lý GPO mặc định là gì?", options: ["OU → Domain → Site", "Site → Domain → OU", "Domain → Site → OU", "Site → OU → Domain"], correct: 1 },
    { question: "LSDOU là viết tắt của gì?", options: ["Local – Site – Domain – OU", "Local – Security – Domain – OU", "Logon – Site – Domain – OU", "Local – System – Domain – OU"], correct: 0 },
    { question: "GPO nào có mức ưu tiên cao nhất?", options: ["Site GPO", "Domain GPO", "OU GPO gần object nhất", "Local GPO"], correct: 2 },
    { question: "GPO inheritance là gì?", options: ["GPO bị xóa", "GPO được kế thừa từ cấp trên", "GPO không áp dụng", "GPO bị sao lưu"], correct: 1 },
    { question: "Block Inheritance dùng để làm gì?", options: ["Chặn GPO từ cấp trên", "Chặn user", "Chặn computer", "Chặn replication"], correct: 0 },
    { question: "Enforced (No Override) có tác dụng gì?", options: ["Cho phép block", "Bắt buộc GPO áp dụng, không bị block", "Chặn GPO", "Xóa GPO"], correct: 1 },
    { question: "Loopback Processing dùng khi nào?", options: ["Áp dụng GPO theo user", "Áp dụng GPO theo computer", "Áp dụng GPO theo DNS", "Áp dụng GPO theo group"], correct: 1 },
    { question: "Loopback Merge khác Replace ở điểm nào?", options: ["Merge ghi đè toàn bộ", "Replace giữ lại GPO user", "Merge kết hợp GPO user", "Replace không dùng được"], correct: 2 },
    { question: "Security Filtering dùng để làm gì?", options: ["Chọn user/computer được áp dụng GPO", "Chọn OU", "Chọn domain", "Chọn site"], correct: 0 },
    { question: "WMI Filtering dùng để làm gì?", options: ["Lọc theo IP", "Lọc theo hệ điều hành, phần cứng", "Lọc theo user", "Lọc theo domain"], correct: 1 },
    { question: "GPO Preference khác GPO Policy ở điểm nào?", options: ["Không áp dụng", "User có thể thay đổi lại cấu hình", "Không dùng được", "Không áp dụng cho computer"], correct: 1 },
    { question: "GPO Policy có đặc điểm gì?", options: ["User có thể thay đổi", "Áp dụng tạm thời", "Bắt buộc, user không đổi được", "Chỉ dùng cho admin"], correct: 2 },
    { question: "Lệnh cập nhật GPO ngay lập tức là gì?", options: ["gpresult", "gpupdate /force", "ipconfig /renew", "net use"], correct: 1 },
    { question: "Lệnh kiểm tra GPO đang áp dụng là gì?", options: ["gpupdate", "gpedit.msc", "gpresult /r", "eventvwr"], correct: 2 },
    { question: "GPO được lưu trữ ở đâu?", options: ["DNS", "SYSVOL và AD database", "DHCP", "IIS"], correct: 1 },
    { question: "GPO có thể backup để làm gì?", options: ["Tăng tốc hệ thống", "Phục hồi khi lỗi", "Phân quyền user", "Quản lý domain"], correct: 1 },
    { question: "Khi GPO không áp dụng, nguyên nhân phổ biến là gì?", options: ["DNS lỗi", "Security filtering sai", "DHCP lỗi", "FSMO lỗi"], correct: 1 },
    { question: "GPO quản lý password thông qua đâu?", options: ["Local Policy", "Domain Policy", "OU Policy", "Site Policy"], correct: 1 },
    { question: "Fine-Grained Password Policy dùng để làm gì?", options: ["Áp dụng nhiều chính sách mật khẩu", "Áp dụng cho computer", "Áp dụng cho site", "Áp dụng cho trust"], correct: 0 },
    { question: "GPO có thể dùng để làm gì sau đây?", options: ["Cài phần mềm", "Chặn USB", "Áp dụng script", "Tất cả các đáp án trên"], correct: 3 },
    { question: "GPO áp dụng chậm thường do nguyên nhân nào?", options: ["DNS lỗi", "Replication chậm", "Network chậm", "Tất cả các đáp án trên"], correct: 3 },
    { question: "Local GPO có hiệu lực khi nào?", options: ["Khi không có domain GPO", "Khi join domain", "Khi có OU", "Khi có trust"], correct: 0 },
    { question: "GPO có rollback được không?", options: ["Không", "Có, bằng restore từ backup", "Tự động", "Chỉ Windows 2019"], correct: 1 },
    { question: "Best practice khi triển khai GPO là gì?", options: ["Tạo nhiều GPO nhỏ, rõ ràng", "Dồn hết vào 1 GPO", "Không dùng filter", "Không backup"], correct: 0 }
];

// Đề 9: DNS & RODC - 30 câu
const questionsSet9 = [
    { question: "DNS là viết tắt của gì?", options: ["Domain Network System", "Data Name System", "Domain Name System", "Dynamic Name System"], correct: 2 },
    { question: "Chức năng chính của DNS là gì?", options: ["Cấp IP", "Phân giải tên miền sang địa chỉ IP", "Quản lý user", "Sao lưu domain"], correct: 1 },
    { question: "Trong môi trường Active Directory, DNS có vai trò gì?", options: ["Không quan trọng", "Rất quan trọng cho xác thực và đăng nhập", "Chỉ dùng cho Internet", "Chỉ dùng cho DHCP"], correct: 1 },
    { question: "Loại zone nào được khuyến nghị dùng cho AD?", options: ["Primary Zone", "Secondary Zone", "Stub Zone", "AD-Integrated Zone"], correct: 3 },
    { question: "AD-Integrated Zone có ưu điểm gì?", options: ["Không cần replication", "Replication thông qua AD", "Chỉ đọc", "Không bảo mật"], correct: 1 },
    { question: "Forward Lookup Zone dùng để làm gì?", options: ["IP → Tên", "Tên → IP", "Tên → MAC", "MAC → IP"], correct: 1 },
    { question: "Reverse Lookup Zone dùng để làm gì?", options: ["Tên → IP", "IP → Tên", "Domain → User", "User → Domain"], correct: 1 },
    { question: "Bản ghi DNS nào ánh xạ hostname với IPv4?", options: ["AAAA", "MX", "A", "CNAME"], correct: 2 },
    { question: "Bản ghi AAAA dùng để làm gì?", options: ["IPv4", "IPv6", "Mail", "Alias"], correct: 1 },
    { question: "Bản ghi CNAME có tác dụng gì?", options: ["Chỉ mail", "Tạo alias cho hostname", "Chỉ dùng cho AD", "Phân quyền"], correct: 1 },
    { question: "Bản ghi MX dùng để làm gì?", options: ["Xác thực domain", "Chỉ định mail server", "Chỉ định DC", "Phân quyền"], correct: 1 },
    { question: "Bản ghi SRV trong AD dùng để làm gì?", options: ["Phân giải web", "Xác định Domain Controller và dịch vụ AD", "Phân giải IP", "Chỉ dùng cho mail"], correct: 1 },
    { question: "Dynamic DNS Update là gì?", options: ["Update thủ công", "Tự động cập nhật bản ghi DNS", "Sao lưu DNS", "Xóa DNS"], correct: 1 },
    { question: "Secure Dynamic Update có đặc điểm gì?", options: ["Ai cũng update được", "Chỉ client/domain hợp lệ mới update", "Không dùng AD", "Không bảo mật"], correct: 1 },
    { question: "DNS Forwarder dùng để làm gì?", options: ["Sao lưu DNS", "Chuyển truy vấn DNS ra ngoài", "Xóa cache", "Phân quyền user"], correct: 1 },
    { question: "Conditional Forwarder dùng khi nào?", options: ["Cho tất cả domain", "Cho domain cụ thể", "Chỉ Internet", "Chỉ nội bộ"], correct: 1 },
    { question: "Lệnh kiểm tra phân giải DNS là gì?", options: ["ping", "tracert", "nslookup", "ipconfig"], correct: 2 },
    { question: "Lệnh xóa cache DNS trên client là gì?", options: ["ipconfig /release", "ipconfig /flushdns", "ipconfig /renew", "netsh dns"], correct: 1 },
    { question: "Nguyên nhân phổ biến khiến user không login domain là gì?", options: ["DHCP lỗi", "DNS lỗi", "GPO lỗi", "FSMO lỗi"], correct: 1 },
    { question: "RODC là viết tắt của gì?", options: ["Read-Only Domain Controller", "Remote Office Domain Controller", "Replicated Online Domain Controller", "Recovery Object Domain Controller"], correct: 0 },
    { question: "RODC thường được triển khai ở đâu?", options: ["Datacenter chính", "Chi nhánh, site xa", "Cloud", "Core network"], correct: 1 },
    { question: "Ưu điểm lớn nhất của RODC là gì?", options: ["Nhanh hơn DC thường", "Bảo mật cao", "Có FSMO", "Có thể ghi dữ liệu"], correct: 1 },
    { question: "RODC có thể ghi dữ liệu AD không?", options: ["Có", "Không", "Tùy cấu hình", "Tùy domain"], correct: 1 },
    { question: "Password Replication Policy (PRP) dùng để làm gì trên RODC?", options: ["Cho phép ghi password", "Xác định account được cache mật khẩu", "Xóa password", "Đồng bộ password"], correct: 1 },
    { question: "RODC có giữ password của Domain Admin không?", options: ["Có", "Không", "Tùy cấu hình", "Tùy trust"], correct: 1 },
    { question: "RODC có giữ FSMO role không?", options: ["Có", "Không", "Chỉ RID", "Chỉ PDC"], correct: 1 },
    { question: "RODC có thể là Global Catalog không?", options: ["Không", "Có", "Chỉ Windows 2019", "Chỉ domain nhỏ"], correct: 1 },
    { question: "RODC giúp giảm rủi ro gì?", options: ["DNS lỗi", "Lộ mật khẩu khi DC bị đánh cắp", "DHCP lỗi", "Trust lỗi"], correct: 1 },
    { question: "Best practice cho DNS trong domain là gì?", options: ["Không dùng AD-integrated", "DC phải trỏ DNS về chính nó", "Chỉ dùng DNS ngoài", "Không dùng forwarder"], correct: 1 },
    { question: "Kết luận đúng nhất về DNS & RODC là gì?", options: ["Không quan trọng", "Là nền tảng cho AD hoạt động ổn định và bảo mật", "Chỉ dùng cho Internet", "Chỉ dùng cho chi nhánh"], correct: 1 }
];

// Đề 10: REMOTE ACCESS - 30 câu
const questionsSet10 = [
    { question: "Remote Access dùng để làm gì?", options: ["Quản lý user", "Truy cập máy tính/tài nguyên từ xa", "Cấp IP", "Phân giải tên"], correct: 1 },
    { question: "Dịch vụ Remote Desktop sử dụng giao thức nào?", options: ["HTTP", "FTP", "RDP", "SSH"], correct: 2 },
    { question: "Cổng (port) mặc định của RDP là bao nhiêu?", options: ["21", "22", "80", "3389"], correct: 3 },
    { question: "Điều kiện để một máy được Remote Desktop là gì?", options: ["Cài DNS", "Bật Remote Desktop", "Cài DHCP", "Join workgroup"], correct: 1 },
    { question: "Nhóm nào được phép đăng nhập Remote Desktop mặc định?", options: ["Guests", "Users", "Administrators", "Power Users"], correct: 2 },
    { question: "Network Level Authentication (NLA) dùng để làm gì?", options: ["Tăng tốc RDP", "Xác thực trước khi tạo phiên RDP", "Chia sẻ màn hình", "Mã hóa dữ liệu"], correct: 1 },
    { question: "Ưu điểm của NLA là gì?", options: ["Giảm tải CPU", "Tăng bảo mật", "Tăng tốc mạng", "Dễ cấu hình"], correct: 1 },
    { question: "VPN là viết tắt của gì?", options: ["Virtual Private Network", "Virtual Public Network", "Verified Private Network", "Virtual Protected Network"], correct: 0 },
    { question: "Mục đích chính của VPN là gì?", options: ["Chia sẻ file", "Truy cập mạng nội bộ qua Internet an toàn", "Cấp IP", "Quản lý domain"], correct: 1 },
    { question: "VPN Remote Access dùng trong trường hợp nào?", options: ["Kết nối 2 mạng LAN", "Người dùng truy cập từ xa vào mạng nội bộ", "Sao lưu dữ liệu", "Cấp quyền user"], correct: 1 },
    { question: "VPN Site-to-Site dùng để làm gì?", options: ["Kết nối user từ xa", "Kết nối 2 mạng LAN với nhau", "Kết nối DNS", "Kết nối DHCP"], correct: 1 },
    { question: "Giao thức VPN nào không còn được khuyến nghị do yếu bảo mật?", options: ["L2TP/IPsec", "SSTP", "IKEv2", "PPTP"], correct: 3 },
    { question: "PPTP sử dụng giao thức nào để mã hóa?", options: ["SSL", "IPsec", "MPPE", "TLS"], correct: 2 },
    { question: "L2TP thường đi kèm với giao thức nào để bảo mật?", options: ["SSL", "TLS", "IPsec", "SSH"], correct: 2 },
    { question: "SSTP hoạt động trên cổng nào?", options: ["21", "22", "80", "443"], correct: 3 },
    { question: "Ưu điểm của SSTP là gì?", options: ["Không mã hóa", "Dễ bị chặn firewall", "Chạy qua HTTPS, dễ vượt firewall", "Chỉ dùng nội bộ"], correct: 2 },
    { question: "IKEv2 có ưu điểm gì nổi bật?", options: ["Dễ cấu hình", "Tốc độ chậm", "Hỗ trợ reconnect khi đổi mạng", "Không mã hóa"], correct: 2 },
    { question: "RRAS là viết tắt của gì?", options: ["Remote Routing and Access Service", "Routing and Remote Access Service", "Remote Resource Access Service", "Routing Resource Access System"], correct: 1 },
    { question: "RRAS dùng để làm gì trong Windows Server?", options: ["DNS", "DHCP", "VPN và Routing", "File Server"], correct: 2 },
    { question: "RRAS hỗ trợ chức năng nào sau đây?", options: ["VPN", "NAT", "Routing", "Tất cả các đáp án trên"], correct: 3 },
    { question: "NAT trong RRAS dùng để làm gì?", options: ["Phân giải tên", "Chuyển IP private sang public", "Xác thực user", "Quản lý domain"], correct: 1 },
    { question: "Remote Desktop Services (RDS) khác RDP thế nào?", options: ["Không khác", "RDS cho nhiều user đăng nhập cùng lúc", "RDP chỉ dùng cho admin", "RDS không cần license"], correct: 1 },
    { question: "RDS CAL dùng để làm gì?", options: ["Cấp IP", "Cấp quyền DNS", "Cấp license cho RDS", "Cấp quyền domain"], correct: 2 },
    { question: "Remote Access có thể xác thực user bằng gì?", options: ["Local account", "Domain account", "Certificate", "Tất cả các đáp án trên"], correct: 3 },
    { question: "Ưu điểm của VPN so với Remote Desktop là gì?", options: ["Xem màn hình từ xa", "Truy cập toàn bộ mạng nội bộ", "Chỉ dùng cho admin", "Không cần bảo mật"], correct: 1 },
    { question: "Nguyên nhân phổ biến khiến VPN không kết nối được là gì?", options: ["DNS lỗi", "Firewall chặn port", "GPO lỗi", "FSMO lỗi"], correct: 1 },
    { question: "Best practice bảo mật Remote Desktop là gì?", options: ["Mở port 3389 cho tất cả", "Dùng mật khẩu yếu", "Bật NLA và giới hạn user", "Không dùng firewall"], correct: 2 },
    { question: "VPN dùng cơ chế nào để bảo mật dữ liệu?", options: ["Plain text", "Encryption", "Compression", "Routing"], correct: 1 },
    { question: "Remote Desktop có thể bị tấn công kiểu nào phổ biến?", options: ["SQL Injection", "Brute force", "XSS", "CSRF"], correct: 1 },
    { question: "Kết luận đúng nhất về Remote Access là gì?", options: ["Không quan trọng", "Giúp truy cập từ xa an toàn nếu cấu hình đúng", "Luôn không an toàn", "Chỉ dùng trong LAN"], correct: 1 }
];

// Đề 11: ĐỊNH TUYẾN (RIP & OSPF) - 30 câu
const questionsSet11 = [
    { question: "RIP là giao thức định tuyến loại nào?", options: ["Link-state", "Distance-vector", "Hybrid", "Path-vector"], correct: 1 },
    { question: "Metric của RIP là gì?", options: ["Bandwidth", "Delay", "Hop count", "Cost"], correct: 2 },
    { question: "Số hop tối đa của RIP là bao nhiêu?", options: ["10", "15", "16", "Không giới hạn"], correct: 1 },
    { question: "Hop count = 16 trong RIP có ý nghĩa gì?", options: ["Tuyến tốt nhất", "Tuyến ưu tiên", "Tuyến không hợp lệ", "Tuyến backup"], correct: 2 },
    { question: "RIP gửi bảng định tuyến theo chu kỳ bao lâu?", options: ["10 giây", "20 giây", "30 giây", "60 giây"], correct: 2 },
    { question: "RIP sử dụng cổng (port) nào?", options: ["TCP 179", "UDP 520", "UDP 67", "TCP 443"], correct: 1 },
    { question: "RIPv1 có đặc điểm nào sau đây?", options: ["Hỗ trợ VLSM", "Không hỗ trợ VLSM", "Có authentication", "Multicast update"], correct: 1 },
    { question: "RIPv2 cải tiến gì so với RIPv1?", options: ["Dùng TCP", "Hỗ trợ VLSM và authentication", "Không dùng hop count", "Không gửi định kỳ"], correct: 1 },
    { question: "RIPv2 gửi update bằng hình thức nào?", options: ["Broadcast", "Unicast", "Multicast", "Anycast"], correct: 2 },
    { question: "Vấn đề lớn nhất của RIP là gì?", options: ["Bảo mật kém", "Hội tụ chậm", "Cấu hình khó", "Không tương thích"], correct: 1 },
    { question: "Split Horizon dùng để làm gì trong RIP?", options: ["Tăng tốc truyền dữ liệu", "Ngăn loop định tuyến", "Tăng bảo mật", "Sao lưu bảng định tuyến"], correct: 1 },
    { question: "Poison Reverse có tác dụng gì?", options: ["Tăng metric", "Báo tuyến lỗi", "Ngăn loop định tuyến", "Cấp phát IP"], correct: 2 },
    { question: "Triggered Update xảy ra khi nào?", options: ["Theo chu kỳ", "Khi có thay đổi tuyến", "Khi khởi động router", "Khi lỗi DNS"], correct: 1 },
    { question: "RIP phù hợp với mạng nào?", options: ["Mạng lớn, phức tạp", "Mạng nhiều site", "Mạng nhỏ, đơn giản", "Mạng ISP"], correct: 2 },
    { question: "Kết luận đúng nhất về RIP là gì?", options: ["Hiệu suất cao", "Dùng cho mạng lớn", "Dễ cấu hình nhưng hạn chế", "Phức tạp, khó học"], correct: 2 },
    { question: "OSPF là giao thức định tuyến loại nào?", options: ["Distance-vector", "Link-state", "Hybrid", "Path-vector"], correct: 1 },
    { question: "OSPF sử dụng thuật toán nào?", options: ["Bellman-Ford", "Dijkstra (SPF)", "A*", "Flooding"], correct: 1 },
    { question: "Metric của OSPF là gì?", options: ["Hop count", "Delay", "Cost", "Bandwidth trực tiếp"], correct: 2 },
    { question: "Cost của OSPF thường dựa trên yếu tố nào?", options: ["Delay", "Bandwidth", "Số router", "CPU"], correct: 1 },
    { question: "OSPF sử dụng giao thức tầng vận chuyển nào?", options: ["TCP", "UDP", "ICMP", "Không dùng TCP/UDP"], correct: 3 },
    { question: "OSPF hội tụ nhanh hơn RIP vì sao?", options: ["Gửi định kỳ nhanh hơn", "Dùng link-state và SPF", "Ít router hơn", "Ít update hơn"], correct: 1 },
    { question: "OSPF chia mạng thành các vùng để làm gì?", options: ["Tăng bảo mật", "Giảm kích thước bảng định tuyến", "Tăng tốc hội tụ", "B và C đúng"], correct: 3 },
    { question: "Area 0 trong OSPF còn gọi là gì?", options: ["Stub Area", "Backbone Area", "NSSA", "Transit Area"], correct: 1 },
    { question: "Router kết nối giữa các area gọi là gì?", options: ["Internal Router", "Backbone Router", "ABR (Area Border Router)", "ASBR"], correct: 2 },
    { question: "Router kết nối OSPF với mạng ngoài (RIP, BGP) gọi là gì?", options: ["ABR", "Internal Router", "ASBR", "Backbone Router"], correct: 2 },
    { question: "OSPF sử dụng địa chỉ multicast nào để gửi update?", options: ["224.0.0.1", "224.0.0.2", "224.0.0.5 và 224.0.0.6", "224.0.0.9"], correct: 2 },
    { question: "DR và BDR được bầu trong trường hợp nào?", options: ["Point-to-point", "Broadcast và NBMA", "Loopback", "WAN"], correct: 1 },
    { question: "Mục đích của DR/BDR là gì?", options: ["Tăng bảo mật", "Giảm số lượng LSAs trao đổi", "Tăng băng thông", "Chống loop"], correct: 1 },
    { question: "OSPF hỗ trợ VLSM không?", options: ["Không", "Có", "Chỉ OSPFv3", "Tùy phiên bản"], correct: 1 },
    { question: "Kết luận đúng nhất về OSPF là gì?", options: ["Chỉ dùng cho mạng nhỏ", "Hội tụ nhanh, phù hợp mạng lớn", "Không bảo mật", "Dễ hơn RIP"], correct: 1 }
];
